# Generated by Django 3.2.25 on 2026-02-02 15:11

from datetime import datetime

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("api", "0001_initial"),
        ("api", "0002_auto_20210827_0826"),
        ("api", "0003_delete_job"),
        ("api", "0004_blank_fields"),
        ("api", "0005_dataset_dataset_conf"),
        ("api", "0006_switch_dataset_spectro_ownership"),
        ("api", "0007_auto_20211117_1245"),
        ("api", "0008_annotationcampaign_annotation_scope"),
        ("api", "0009_add_blanks_choices"),
        ("api", "0010_annotationcampaign_annotators"),
        ("api", "0011_remove_useless_collectiondataset"),
        ("api", "0012_auto_20230417_1701"),
        ("api", "0013_auto_20230418_1206"),
        ("api", "0014_auto_20230423_1909"),
        ("api", "0015_auto_20230423_1909"),
        ("api", "0016_auto_20230428_1023"),
        ("api", "0017_auto_20230428_1141"),
        ("api", "0018_alter_annotationtask_status"),
        ("api", "0019_auto_20230504_1019"),
        ("api", "0020_alter_annotationtask_status"),
        ("api", "0021_change_zoom_level_format"),
        ("api", "0022_annotationcomment"),
        ("api", "0023_news"),
        ("api", "0024_add_created_at_fields"),
        ("api", "0025_add_spectroconfig"),
        ("api", "0026_add_dataset_new_ForeignKey"),
        ("api", "0027_clean_dataset_and_spectroconfig"),
        ("api", "0028_confidence_indicator_set"),
        ("api", "0029_alter_news_options"),
        ("api", "0030_spectroconfig_name_dataset_unicity_constraint"),
        ("api", "0031_delete_news"),
        ("api", "0031_allow_blank_collections_confidence_set"),
        ("api", "0032_merge_20240108_1138"),
        ("api", "0033_double_check_feature"),
        ("api", "0034_alter_annotationresult_dataset_file"),
        ("api", "0035_add_campaign_archivage"),
        ("api", "0036_alter_annotationcampaignarchive_date"),
        ("api", "0037_replace_campaign_start-end_by_deadline"),
        ("api", "0035_rename_tag_label"),
        ("api", "0036_rename_annotationset_labelset"),
        ("api", "0038_merge_20240410_1746"),
        ("api", "0039_update_spectro_config"),
        ("api", "0040_alter_spectroconfig_zscore_duration"),
        ("api", "0041_audiometadatum_audio_file_count"),
        ("api", "0042_audiometadatum_audio_file_dataset_duration"),
        ("api", "0043_remove_spectroconfig_number_spectra"),
        ("api", "0044_alter_annotationcampaign_options"),
        ("api", "0045_custom_scale"),
        ("api", "0046_alter_multilinearscale_inner_scales"),
        ("api", "0047_auto_20240703_1515"),
        ("api", "0044_alter_dataset_dataset_type"),
        ("api", "0045_merge_20240701_0956"),
        ("api", "0048_merge_20240723_1122"),
        ("api", "0049_alter_annotationtask_options"),
        ("api", "0050_alter_annotationtask"),
        ("api", "0050b_alter_annotationtask"),
        ("api", "0051_dataset_file_start_end"),
        ("api", "0052_dataset_file_start_end_finalise"),
        ("api", "0053_auto_20241001_1633"),
        ("api", "0054_annotationfilerange"),
        ("api", "0055_fill_annotationfilerange"),
        ("api", "0056_clean_duplicated_tasks"),
        ("api", "0057_add_task_constraints"),
        ("api", "0058_auto_20241009_0909"),
        ("api", "0059_annotationfilerange_files_count"),
        ("api", "0060_update_annotation_comment"),
        ("api", "0061_auto_20241016_1458"),
        ("api", "0062_auto_20241025_1157"),
        ("api", "0063_annotationcampaign_annotators"),
        ("api", "0064_annotationcampaign_labels_with_acoustic_features"),
        ("api", "0065_acoustic_features"),
        ("api", "0064_sample_bits"),
        ("api", "0066_auto_20241216_1657"),
        ("api", "0067_alter_confidenceindicator_table"),
        ("api", "0068_final_acoustic_features"),
        ("api", "0065_confidence_set_indicator_relation"),
        ("api", "0069_merge_20250213_1409"),
        ("api", "0066_file_range_limits"),
        ("api", "0070_merge_0066_file_range_limits_0069_merge_20250213_1409"),
        ("api", "0067_alter_datasetfile_options"),
        ("api", "0071_merge_20250218_1502"),
        ("api", "0072_annotationresult_annotator_expertise_level"),
        ("api", "0073_annotationresulttype"),
        ("api", "0074_annotationcampaign_allow_point_annotation"),
        ("api", "0075_dataset_related_channel_configuration"),
        ("api", "0076_spectrogram_tuning"),
        ("api", "0077_annotationresult_updated_to"),
        ("api", "0078_annotationcampaignphase"),
        ("api", "0079_annotationresult_create_update_dates"),
        ("api", "0080_alter_annotationcampaign_label_set"),
        ("api", "0081_alter_dataset_related_channel_configuration"),
        ("api", "0082_label_metadatax_label"),
        ("api", "0083_update_filerange_bornes_to_datetime"),
        ("api", "0084_migrate_osekit__archive"),
        ("api", "0085_migrate_osekit__annotation_session"),
        ("api", "0086_migrate_osekit__annotation_validation"),
        ("api", "0087_migrate_osekit__analysis"),
        ("api", "0088_migrate_osekit__spectrogram"),
        ("api", "0089_migrate_osekit__campaign"),
        ("api", "0090_migrate_osekit__phase"),
        ("api", "0091_migrate_osekit__annotation"),
        ("api", "0092_migrate_osekit__annotation_task"),
        ("api", "0093_migrate_osekit__annotation_comment"),
        ("api", "0094_migrate_osekit__detector"),
        ("api", "0095_migrate_osekit__clean"),
        ("api", "0096_migrate_osekit__add_start_end_to_analysis"),
        ("api", "0097_auto_20260105_1711"),
    ]

    initial = True

    dependencies = [
        ("ontology", "0005_table_names"),
        ("acquisition", "0005_clean"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0006_audiofile_detectionfile"),
        ("equipment", "0003_clean"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcousticFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_frequency",
                    models.FloatField(
                        blank=True,
                        help_text="[Hz] Frequency at the beginning of the signal",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "end_frequency",
                    models.FloatField(
                        blank=True,
                        help_text="[Hz] Frequency at the end of the signal",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "relative_max_frequency_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of relative maximum frequency in the signal",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "relative_min_frequency_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of relative minimum frequency in the signal",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "has_harmonics",
                    models.BooleanField(
                        blank=True, help_text="If the signal has harmonics", null=True
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLAT", "Flat"),
                            ("ASC", "Ascending"),
                            ("DESC", "Descending"),
                            ("MOD", "Modulated"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "steps_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of steps (flat segment) in the signal",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Acoustic features",
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[("W", "Weak"), ("P", "Point"), ("B", "Box")],
                        help_text="Type of the annotation",
                    ),
                ),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("start_frequency", models.FloatField(blank=True, null=True)),
                ("end_frequency", models.FloatField(blank=True, null=True)),
                (
                    "annotator_expertise_level",
                    models.TextField(
                        blank=True,
                        choices=[("E", "Expert"), ("A", "Average"), ("N", "Novice")],
                        help_text="Expertise level of the annotator.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acoustic_features",
                    models.OneToOneField(
                        blank=True,
                        help_text="Acoustic features add a better description to the signal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotation",
                        to="api.acousticfeatures",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("instructions_url", models.URLField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("allow_point_annotation", models.BooleanField(default=False)),
                ("allow_image_tuning", models.BooleanField(default=False)),
                ("allow_colormap_tuning", models.BooleanField(default=False)),
                ("colormap_default", models.TextField(blank=True, null=True)),
                (
                    "colormap_inverted_default",
                    models.BooleanField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[("A", "Annotation"), ("V", "Verification")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "annotation_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="api.annotationcampaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_phases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ended_phases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("C", "Created"), ("F", "Finished")], default="C"
                    ),
                ),
                (
                    "annotation_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_tasks",
                        to="api.annotationphase",
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["spectrogram__start", "id"],
            },
        ),
        migrations.CreateModel(
            name="Colormap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Confidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ConfidenceIndicatorSetIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "confidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_relations",
                        to="api.confidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("path", models.CharField(max_length=255)),
                ("legacy", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_channel_configurations",
                    models.ManyToManyField(
                        related_name="datasets", to="acquisition.ChannelConfiguration"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Detector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="equipment.acousticdetectorspecification",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nfft", models.IntegerField()),
                ("window_size", models.IntegerField()),
                ("overlap", models.DecimalField(decimal_places=2, max_digits=3)),
                ("sampling_frequency", models.PositiveIntegerField()),
                ("scaling", models.CharField(blank=True, max_length=50, null=True)),
                ("legacy", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {
                    (
                        "nfft",
                        "window_size",
                        "overlap",
                        "sampling_frequency",
                        "scaling",
                        "legacy",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "metadatax_label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ontology.label",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinearScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("ratio", models.FloatField(default=1)),
                ("min_value", models.FloatField()),
                ("max_value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("session_output", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="SpectrogramAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("path", models.CharField(max_length=255)),
                ("legacy", models.BooleanField(default=False)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "data_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Duration of the segmented data (in s)",
                        null=True,
                    ),
                ),
                ("dynamic_min", models.FloatField()),
                ("dynamic_max", models.FloatField()),
                (
                    "colormap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spectrogram_analysis",
                        to="api.colormap",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrogram_analysis",
                        to="api.dataset",
                    ),
                ),
                (
                    "fft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spectrogram_analysis",
                        to="api.fft",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spectrogram_analysis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Spectrogram analysis",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Spectrogram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "analysis",
                    models.ManyToManyField(
                        related_name="spectrograms", to="api.SpectrogramAnalysis"
                    ),
                ),
                (
                    "format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.fileformat",
                    ),
                ),
            ],
            options={
                "ordering": ("start", "id"),
            },
        ),
        migrations.CreateModel(
            name="MultiLinearScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "inner_scales",
                    models.ManyToManyField(
                        related_name="outer_scales", to="api.LinearScale"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacySpectrogramConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder", models.CharField(max_length=255)),
                (
                    "audio_files_subtypes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("channel_count", models.IntegerField(blank=True, null=True)),
                ("file_overlap", models.IntegerField(blank=True, null=True)),
                ("zoom_level", models.IntegerField()),
                ("hp_filter_min_frequency", models.IntegerField()),
                ("data_normalization", models.CharField(max_length=255)),
                ("frequency_resolution", models.FloatField()),
                ("spectrogram_normalization", models.CharField(max_length=255)),
                (
                    "zscore_duration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "window_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("peak_voltage", models.FloatField(blank=True, null=True)),
                ("sensitivity_dB", models.FloatField(blank=True, null=True)),
                ("temporal_resolution", models.FloatField(blank=True, null=True)),
                ("gain_dB", models.FloatField(blank=True, null=True)),
                (
                    "linear_frequency_scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.linearscale",
                    ),
                ),
                (
                    "multi_linear_frequency_scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.multilinearscale",
                    ),
                ),
                (
                    "spectrogram_analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_configuration",
                        to="api.spectrogramanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("labels", models.ManyToManyField(to="api.Label")),
            ],
        ),
        migrations.CreateModel(
            name="DetectorConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configuration", models.TextField()),
                (
                    "detector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="api.detector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfidenceSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "confidence_indicators",
                    models.ManyToManyField(
                        related_name="confidence_indicator_sets",
                        through="api.ConfidenceIndicatorSetIndicator",
                        to="api.Confidence",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="confidenceindicatorsetindicator",
            name="confidence_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicator_relations",
                to="api.confidenceset",
            ),
        ),
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_valid", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="api.annotation",
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_results_validation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationTaskSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.annotationtask",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.session"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annotationtask",
            name="sessions",
            field=models.ManyToManyField(
                related_name="annotation_tasks",
                through="api.AnnotationTaskSession",
                to="api.Session",
            ),
        ),
        migrations.AddField(
            model_name="annotationtask",
            name="spectrogram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotation_tasks",
                to="api.spectrogram",
            ),
        ),
        migrations.CreateModel(
            name="AnnotationFileRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_file_index",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "last_file_index",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("from_datetime", models.DateTimeField()),
                ("to_datetime", models.DateTimeField()),
                ("files_count", models.PositiveIntegerField()),
                (
                    "annotation_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_file_ranges",
                        to="api.annotationphase",
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_file_ranges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_file_index"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_comments",
                        to="api.annotation",
                    ),
                ),
                (
                    "annotation_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_comments",
                        to="api.annotationphase",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spectrogram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_comments",
                        to="api.spectrogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationCampaignAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.spectrogramanalysis",
                    ),
                ),
                (
                    "annotation_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.annotationcampaign",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="analysis",
            field=models.ManyToManyField(
                related_name="annotation_campaigns",
                through="api.AnnotationCampaignAnalysis",
                to="api.SpectrogramAnalysis",
            ),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="archive",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotation_campaign",
                to="api.archive",
            ),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="confidence_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.confidenceset",
            ),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotation_campaigns",
                to="api.dataset",
            ),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="label_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.labelset",
            ),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="labels_with_acoustic_features",
            field=models.ManyToManyField(blank=True, to="api.Label"),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogramanalysis",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="annotation_phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.annotationphase",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="annotator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="confidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.confidence",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="detector_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.detectorconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="is_update_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_to",
                to="api.annotation",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.label"
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="spectrogram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogram",
            ),
        ),
        migrations.AddConstraint(
            model_name="spectrogramanalysis",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("legacy", True),
                    models.Q(("data_duration__isnull", False), ("legacy", False)),
                    _connector="OR",
                ),
                name="spectrogram_analysis_legacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="spectrogram",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lt", django.db.models.expressions.F("end"))),
                name="start is lower than end",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyspectrogramconfiguration",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("linear_frequency_scale__isnull", True),
                        ("multi_linear_frequency_scale__isnull", False),
                    ),
                    models.Q(
                        ("linear_frequency_scale__isnull", False),
                        ("multi_linear_frequency_scale__isnull", True),
                    ),
                    models.Q(
                        ("linear_frequency_scale__isnull", True),
                        ("multi_linear_frequency_scale__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="legacy_spectrogram_configuration_max_one_scale",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="detectorconfiguration",
            unique_together={("configuration", "detector")},
        ),
        migrations.AlterUniqueTogether(
            name="dataset",
            unique_together={("name", "path")},
        ),
        migrations.AddConstraint(
            model_name="confidenceindicatorsetindicator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default", "confidence_set"),
                name="one_default_confidence_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="confidenceindicatorsetindicator",
            constraint=models.UniqueConstraint(
                fields=("confidence", "confidence_set"),
                name="no_duplicate_confidence_in_set",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="annotationvalidation",
            unique_together={("annotation", "annotator")},
        ),
        migrations.AlterUniqueTogether(
            name="annotationtask",
            unique_together={("spectrogram", "annotation_phase", "annotator")},
        ),
        migrations.AlterUniqueTogether(
            name="annotationphase",
            unique_together={("phase", "annotation_campaign")},
        ),
        migrations.AlterUniqueTogether(
            name="annotationcampaignanalysis",
            unique_together={("annotation_campaign", "analysis")},
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("annotator__isnull", True),
                        ("detector_configuration__isnull", False),
                    ),
                    models.Q(
                        ("annotator__isnull", False),
                        ("detector_configuration__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="require_user_or_detector",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("end_frequency__isnull", True),
                        ("end_time__isnull", True),
                        ("start_frequency__isnull", True),
                        ("start_time__isnull", True),
                        ("type", "W"),
                    ),
                    models.Q(
                        ("end_frequency__isnull", True),
                        ("end_time__isnull", True),
                        ("start_frequency__isnull", False),
                        ("start_time__isnull", False),
                        ("type", "P"),
                    ),
                    models.Q(
                        ("end_frequency__isnull", False),
                        ("end_time__isnull", False),
                        ("start_frequency__isnull", False),
                        ("start_time__isnull", False),
                        ("type", "B"),
                    ),
                    _connector="OR",
                ),
                name="Annotation type",
            ),
        ),
    ]
