# Generated by Django 3.2.25 on 2026-02-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_v3_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="acousticfeatures",
            name="does_overlap_other_signals",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acousticfeatures",
            name="frequency_jumps_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acousticfeatures",
            name="has_deterministic_chaos",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acousticfeatures",
            name="has_frequency_jumps",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acousticfeatures",
            name="has_sidebands",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acousticfeatures",
            name="is_intensity_too_low",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acousticfeatures",
            name="has_subharmonics",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
