# Generated by Django 3.2 on 2021-09-10 13:29
import os
from pathlib import PureWindowsPath

from django.conf import settings
from django.db import migrations


def format_path(path):
    return PureWindowsPath(path).as_posix()


def migration_paths(apps, _):
    Dataset = apps.get_model("api", "Dataset")

    for d in Dataset.objects.all():
        splitted = format_path(d.path).split(format_path(settings.DATASET_EXPORT_PATH))
        d.path = splitted.pop()[1:]
        d.save()


def reverse_migration_paths(apps, _):
    Dataset = apps.get_model("api", "Dataset")

    for d in Dataset.objects.all():
        d.path = format_path(os.path.join(settings.DATASET_EXPORT_PATH, d.path))
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_update_acoustic_features"),
    ]

    operations = [
        migrations.RunPython(migration_paths, reverse_migration_paths),
    ]
