# Generated by Django 3.2 on 2021-09-10 13:29
import os
from pathlib import PureWindowsPath

from django.conf import settings
from django.db import migrations
from django.db.models import Count, Q


def format_path(path):
    return PureWindowsPath(path).as_posix()


def clean_paths(apps, _):
    Dataset = apps.get_model("api", "Dataset")

    for d in Dataset.objects.all():
        splitted = format_path(d.path).split(format_path(settings.DATASET_EXPORT_PATH))
        d.path = splitted.pop()[1:]
        d.save()


def reverse_clean_paths(apps, _):
    Dataset = apps.get_model("api", "Dataset")

    for d in Dataset.objects.all():
        d.path = format_path(os.path.join(settings.DATASET_EXPORT_PATH, d.path))
        d.save()


def handle_duplicate_paths(apps, _):
    Dataset = apps.get_model("api", "Dataset")
    SpectrogramAnalysis = apps.get_model("api", "SpectrogramAnalysis")
    AnnotationCampaign = apps.get_model("api", "AnnotationCampaign")
    duplicated_path = (
        Dataset.objects.values("path")
        .annotate(count=Count("path"))
        .order_by("-count")
        .filter(count__gt=1)
        .values_list("path", flat=True)
    )

    for path in duplicated_path:
        kept_dataset = Dataset.objects.filter(path=path).first()
        kept_dataset.name = PureWindowsPath(path).stem
        kept_dataset.save()
        SpectrogramAnalysis.objects.filter(dataset__path=path).update(
            dataset=kept_dataset
        )
        AnnotationCampaign.objects.filter(dataset__path=path).update(
            dataset=kept_dataset
        )
        Dataset.objects.filter(path=path).filter(~Q(id=kept_dataset.id)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_update_acoustic_features"),
    ]

    operations = [
        migrations.RunPython(clean_paths, reverse_clean_paths),
        migrations.RunPython(handle_duplicate_paths, migrations.RunPython.noop),
    ]
