# Generated by Django 3.2.25 on 2026-04-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_format_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpectrogramAnalysisRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spectrogram_path", models.TextField(blank=True, null=True)),
                ("audio_path", models.TextField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.spectrogramanalysis",
                        related_name="spectrogram_relations",
                    ),
                ),
                (
                    "spectrogram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.spectrogram",
                        related_name="analysis_relations",
                    ),
                ),
            ],
            options={
                "unique_together": {("analysis", "spectrogram")},
            },
        ),
        migrations.RenameField(
            model_name="spectrogram",
            old_name="analysis",
            new_name="old_analysis",
        ),
        migrations.AddField(
            model_name="spectrogram",
            name="analysis",
            field=models.ManyToManyField(
                related_name="spectrograms",
                through="api.SpectrogramAnalysisRelation",
                to="api.SpectrogramAnalysis",
            ),
        ),
        migrations.RunSQL(
            """
            INSERT INTO api_spectrogramanalysisrelation (analysis_id, spectrogram_id)
            SELECT spectrogramanalysis_id, spectrogram_id FROM api_spectrogram_old_analysis;
            """,
            """
            INSERT INTO api_spectrogram_old_analysis (spectrogramanalysis_id, spectrogram_id)
            SELECT analysis_id, spectrogram_id FROM api_spectrogramanalysisrelation;
            """,
        ),
        migrations.RemoveField(
            model_name="spectrogram",
            name="old_analysis",
        ),
    ]
