# Generated by Django 3.2.25 on 2026-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_format_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectrogramanalysis",
            name="is_import_completed",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="spectrogramanalysis",
            name="is_import_completed",
            field=models.BooleanField(default=False),
        ),
    ]
