# Generated by Django 3.2.25 on 2026-05-28 12:47

from django.db import migrations, models


def reverse_insert(apps, _):
    SpectrogramAnalysis = apps.get_model("api", "SpectrogramAnalysis")
    MultiLinearScale = apps.get_model("api", "MultiLinearScale")

    for a in SpectrogramAnalysis.objects.all():
        if a.frequency_scale_parts.exists() and a.legacy_configuration:
            multi_scale = MultiLinearScale.objects.create()
            for linear_scale in a.frequency_scale_parts.all():
                multi_scale.inner_scales.add(linear_scale)
            a.legacy_configuration.multi_linear_frequency_scale = multi_scale
            a.legacy_configuration.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_spectrogramanalysisrelation_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectrogramanalysis",
            name="frequency_scale_parts",
            field=models.ManyToManyField(
                related_name="spectrogram_analysis", to="api.LinearScale"
            ),
        ),
        migrations.RunSQL(
            """
                INSERT INTO api_spectrogramanalysis_frequency_scale_parts (spectrogramanalysis_id, linearscale_id)
                SELECT
                    conf.spectrogram_analysis_id,
                    conf.linear_frequency_scale_id
                FROM api_legacyspectrogramconfiguration conf 
                WHERE conf.linear_frequency_scale_id is not null ;
                INSERT INTO api_spectrogramanalysis_frequency_scale_parts (spectrogramanalysis_id, linearscale_id)
                SELECT
                    conf.spectrogram_analysis_id,
                    innerscales.linearscale_id
                FROM api_legacyspectrogramconfiguration conf
                         LEFT JOIN api_multilinearscale multiscale ON multiscale.id = conf.multi_linear_frequency_scale_id
                         LEFT JOIN api_multilinearscale_inner_scales innerscales ON innerscales.multilinearscale_id = multiscale.id
                WHERE conf.multi_linear_frequency_scale_id is not null ;
                """,
            migrations.RunSQL.noop,
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_insert),
        migrations.RemoveConstraint(
            model_name="legacyspectrogramconfiguration",
            name="legacy_spectrogram_configuration_max_one_scale",
        ),
        migrations.RemoveField(
            model_name="legacyspectrogramconfiguration",
            name="linear_frequency_scale",
        ),
        migrations.RemoveField(
            model_name="legacyspectrogramconfiguration",
            name="multi_linear_frequency_scale",
        ),
    ]
