# Generated by Django 3.2.25 on 2026-05-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_spectrogramanalysis_frequency_scale_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="analysis",
        ),
    ]
