# Generated by Django 3.2.25 on 2026-09-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_annotation_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationcampaign",
            name="allow_digital_zoom",
            field=models.BooleanField(default=False),
        ),
    ]
