# Generated by Django 3.2.25 on 2026-09-30 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, ExpressionWrapper, Q, BooleanField, Model

from backend.api.models import AnnotationCampaign


def migrate_campaign_archive_info(apps, _):
    AnnotationCampaign = apps.get_model("api", "AnnotationCampaign")

    for campaign in AnnotationCampaign.objects.filter(archive__isnull=False):
        campaign.archived = True
        campaign.archived_at = campaign.archive.date
        campaign.archived_by = campaign.archive.by_user
        campaign.save()


def reverse_migrate_campaign_archive_info(apps, _):
    AnnotationCampaign = apps.get_model("api", "AnnotationCampaign")
    Archive = apps.get_model("common", "Archive")

    for campaign in AnnotationCampaign.objects.filter(archived=True):
        campaign.archive = Archive.objects.create(
            date=campaign.archived_at,
            by_user=campaign.archived_by,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_archivable_dataset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectrogramanalysis",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="spectrogramanalysis",
            name="archived_at",
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotationcampaign",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            migrate_campaign_archive_info, reverse_migrate_campaign_archive_info
        ),
        migrations.RemoveField(
            model_name="annotationcampaign",
            name="archive",
        ),
    ]
