# Generated by Django 3.2.25 on 2026-09-30 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_phase_archive_info(apps, _):
    AnnotationPhase = apps.get_model("api", "AnnotationPhase")
    AnnotationPhase.objects.filter(archived_at__isnull=False).update(archived=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_archive_to_archivable_abstract"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotationphase",
            old_name="ended_at",
            new_name="archived_at",
        ),
        migrations.RenameField(
            model_name="annotationphase",
            old_name="ended_by",
            new_name="archived_by",
        ),
        migrations.AlterField(
            model_name="annotationphase",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_phases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotationphase",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_phase_archive_info, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="spectrogramanalysis",
            name="archived_by",
        ),
        migrations.DeleteModel(
            name="Archive",
        ),
    ]
