# Generated by Django 3.2.25 on 2026-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_archivable_annotation_phase"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="annotationcampaign",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("archived", True),
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                    ),
                    models.Q(
                        ("archived", False),
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="campaign_archive_info",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationphase",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("archived", True),
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                    ),
                    models.Q(
                        ("archived", False),
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="phase_archive_info",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataset",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("archived", True),
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                    ),
                    models.Q(
                        ("archived", False),
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="dataset_archive_info",
            ),
        ),
    ]
