# Generated by Django 3.2.25 on 2026-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_archive_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annotation",
            name="Annotation type",
        ),
        migrations.RenameField(
            model_name="annotation",
            old_name="end_frequency",
            new_name="max_frequency",
        ),
        migrations.RenameField(
            model_name="annotation",
            old_name="start_frequency",
            new_name="min_frequency",
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("end_time__isnull", True),
                        ("max_frequency__isnull", True),
                        ("min_frequency__isnull", True),
                        ("start_time__isnull", True),
                        ("type", "W"),
                    ),
                    models.Q(
                        ("end_time__isnull", True),
                        ("max_frequency__isnull", True),
                        ("min_frequency__isnull", False),
                        ("start_time__isnull", False),
                        ("type", "P"),
                    ),
                    models.Q(
                        ("end_time__isnull", False),
                        ("max_frequency__isnull", False),
                        ("min_frequency__isnull", False),
                        ("start_time__isnull", False),
                        ("type", "B"),
                    ),
                    _connector="OR",
                ),
                name="Annotation type",
            ),
        ),
    ]
