# Generated by Django 3.2.25 on 2025-07-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_migrate_to_osekit"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            SELECT setval('api_legacyspectrogramconfiguration_id_seq', (SELECT max(id) from api_legacyspectrogramconfiguration));
            SELECT setval('api_dataset_id_seq', (SELECT max(id) from api_dataset));
            SELECT setval('api_spectrogramanalysis_id_seq', (SELECT max(id) from api_spectrogramanalysis));
            SELECT setval('api_spectrogram_id_seq', (SELECT max(id) from api_spectrogram));
            SELECT setval('api_annotation_id_seq', (SELECT max(id) from api_annotation));
            """,
        ),
    ]
