# Generated by Django 3.2.25 on 2025-08-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_migrate_to_osekit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.annotationphase'),
        ),
    ]
