# Generated by Django 3.2.25 on 2025-08-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0085_alter_annotation_annotation_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="spectrogram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogram",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="annotation",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogramanalysis",
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql="""
            UPDATE api_annotation a
            SET analysis_id = sa.spectrogramanalysis_id
            FROM api_spectrogram_analysis sa
            WHERE a.spectrogram_id = sa.spectrogram_id
            """,
            reverse_sql="",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="api.spectrogramanalysis",
            ),
            preserve_default=False,
        ),
    ]
