# Generated by Django 3.2.25 on 2025-08-27 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20250825_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
