# Generated by Django 3.2.25 on 2025-08-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0087_annotationcomment_created_at"),
    ]

    operations = [
        migrations.RunSQL(
            """
                UPDATE postgres.public.api_annotationtask
                SET status = 'F'
                WHERE status='S'
          """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
