# Generated by Django 3.2.25 on 2025-09-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0089_alter_annotationvalidation_is_valid'), ('api', '0090_auto_20250904_1423'), ('api', '0091_remove_fft_fft_legacy'), ('api', '0092_auto_20250909_0903'), ('api', '0093_alter_legacyspectrogramconfiguration_spectrogram_analysis'), ('api', '0094_auto_20250909_0949'), ('api', '0095_alter_fft_window'), ('api', '0096_auto_20250909_1055')]

    dependencies = [
        ('api', '0088_fix_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationvalidation',
            name='is_valid',
            field=models.BooleanField(),
        ),
        migrations.RemoveConstraint(
            model_name='fft',
            name='fft_legacy',
        ),
        migrations.RemoveConstraint(
            model_name='spectrogramanalysis',
            name='spectrogram_analysis_legacy',
        ),
        migrations.AddField(
            model_name='legacyspectrogramconfiguration',
            name='spectrogram_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_configuration', to='api.spectrogramanalysis'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql='\n                UPDATE api_legacyspectrogramconfiguration\n                SET spectrogram_analysis_id=s.id\n                FROM api_spectrogramanalysis s\n                WHERE s.legacy_configuration_id is not null and s.legacy_configuration_id = api_legacyspectrogramconfiguration.id;\n            ',
        ),
        migrations.AlterField(
            model_name='legacyspectrogramconfiguration',
            name='spectrogram_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_configuration', to='api.spectrogramanalysis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legacyspectrogramconfiguration',
            name='spectrogram_analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_configuration', to='api.spectrogramanalysis'),
        ),
        migrations.RemoveField(
            model_name='spectrogramanalysis',
            name='legacy_configuration',
        ),
        migrations.AddConstraint(
            model_name='spectrogramanalysis',
            constraint=models.CheckConstraint(check=models.Q(('data_duration__isnull', False), ('legacy', False)), name='spectrogram_analysis_legacy'),
        ),
        migrations.AlterField(
            model_name='spectrogramanalysis',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spectrogramanalysis',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fft',
            unique_together={('nfft', 'window_size', 'overlap', 'sampling_frequency')},
        ),
        migrations.RemoveField(
            model_name='fft',
            name='window',
        ),
    ]
