# Generated by Django 3.2.25 on 2025-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0089_alter_annotationvalidation_is_valid_squashed_0096_auto_20250909_1055",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="spectrogramanalysis",
            name="spectrogram_analysis_legacy",
        ),
        migrations.AddConstraint(
            model_name="spectrogramanalysis",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("legacy", True),
                    models.Q(("data_duration__isnull", False), ("legacy", False)),
                    _connector="OR",
                ),
                name="spectrogram_analysis_legacy",
            ),
        ),
    ]
