# Generated by Django 3.2.25 on 2025-10-23 13:38

from django.db import migrations


def add_missing_analysis_campaign_links(apps, schema_editor):
    campaign_model = apps.get_model("api", "AnnotationCampaign")
    relation_model = apps.get_model("api", "AnnotationCampaignAnalysis")

    new_relations = []
    for campaign in campaign_model.objects.all():
        if not campaign.dataset:
            continue
        if campaign.analysis.exists():
            continue

        for analysis in campaign.dataset.spectrogram_analysis.all():
            new_relations.append(
                relation_model(
                    annotation_campaign=campaign,
                    analysis=analysis,
                )
            )
    relation_model.objects.bulk_create(new_relations)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0091_auto_20251017_1112"),
    ]

    operations = [
        migrations.RunPython(
            add_missing_analysis_campaign_links, reverse_code=migrations.RunPython.noop
        ),
    ]
