fragment StorageFolder on FolderNode {
    __typename
    name
    path
    error
    stack
}
fragment StorageDataset on DatasetStorageNode {
    __typename
    name
    path
    importStatus
    model {
        id
        annotationCampaigns {
            edges {
                node {
                    isArchived
                }
            }
        }
    }
    error
    stack
}
fragment StorageAnalysis on AnalysisStorageNode {
    __typename
    name
    path
    importStatus
    model {
        annotationCampaigns {
            edges {
                node {
                    isArchived
                }
            }
        }
    }
    error
    stack
}

fragment StorageItem on StorageUnion {
    ... on FolderNode { ...StorageFolder }
    ... on DatasetStorageNode { ...StorageDataset }
    ... on AnalysisStorageNode { ...StorageAnalysis }
}

query browseStorage($path: String!) {
    browse(path: $path) { ...StorageItem }
}
