# Generated by Django 4.2.29 on 2026-03-20 08:13
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0003_format_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportAnalysisBackgroundTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celery_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESS", "Processing"),
                            ("COMPLETE", "Completed"),
                            ("FAIL", "Failed"),
                            ("CANCEL", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("completion_percentage", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("error_trace", models.TextField(blank=True, null=True)),
                ("analysis_path", models.TextField()),
                (
                    "total_spectrograms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("completed_spectrograms", models.PositiveIntegerField(default=0)),
                ("chunk_size", models.PositiveIntegerField(default=200)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_analysis_background_tasks",
                        to="api.spectrogramanalysis",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_analysis_background_tasks",
                        to="api.dataset",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
