query allAnnotationSpectrograms(
    $annotatorID: ID!
    $campaignID: ID!
    $phaseType: AnnotationPhaseType!

    # Pagination
    $limit: Int!
    $offset: Int!

    # Filtering
    $search: String
    $status: AnnotationTaskStatus
    $from: DateTime
    $to: DateTime

    $onlyAssigned: Boolean
    $withAnnotations: Boolean
    $annotationLabel: String
    $annotationConfidence: String
    $annotationDetector: ID
    $annotationAnnotator: ID
    $withAcousticFeatures: Boolean
) {
    allAnnotationSpectrograms(
        # Sort
        limit: $limit
        offset: $offset
        orderBy: "start"

        # Only assigned
        annotator: $annotatorID
        annotationCampaign: $campaignID
        phase: $phaseType
        onlyAssigned: $onlyAssigned

        # Search
        filename_Icontains: $search

        # Dates filters
        end_Gte: $from
        start_Lte: $to

        # Task filters
        annotationTasks_Status: $status

        # Annotation filters
        annotations_Exists: $withAnnotations
        annotations_LabelName: $annotationLabel
        annotations_Confidence_Label: $annotationConfidence
        annotations_Detector: $annotationDetector
        annotations_Annotator: $annotationAnnotator
        annotations_AcousticFeatures_Exists: $withAcousticFeatures
    ) {
        resumeSpectrogramId(phase: $phaseType, campaignId: $campaignID)
        results {
            id
            filename
            start
            duration
            isAssigned(campaignId: $campaignID, phase: $phaseType)

            task(
                phase: $phaseType
                campaignId: $campaignID
            ) {
                status

                userAnnotations(
                    annotator: $annotationAnnotator
                    label_Name: $annotationLabel
                    confidence_Label: $annotationConfidence
                    detectorConfiguration_Detector: $annotationDetector
                    acousticFeatures_Exists: $withAcousticFeatures
                ) {
                    totalCount
                }
                annotationsToCheck(
                    annotator: $annotationAnnotator
                    isUpdated: false # Since I need the count, if it is updated it will be counted on 'userAnnotation'
                    label_Name: $annotationLabel
                    confidence_Label: $annotationConfidence
                    detectorConfiguration_Detector: $annotationDetector
                    acousticFeatures_Exists: $withAcousticFeatures
                ) {
                    totalCount
                }

                validAnnotationsToCheck: annotationsToCheck(
                    annotator: $annotationAnnotator
                    isValidatedBy: $annotatorID
                    label_Name: $annotationLabel
                    confidence_Label: $annotationConfidence
                    detectorConfiguration_Detector: $annotationDetector
                    acousticFeatures_Exists: $withAcousticFeatures
                ) {
                    totalCount
                }
            }
        }
        totalCount
    }
}
