"""Util test case classes with common behavior"""

all_fixtures = [
    "users",
    "dataset",
    "colormap",
    "fft",
    "legacy_spectrogram_configuration",
    "spectrogram",
    "spectrogram_analysis",
    "label_set",
    "label",
    "confidence_set",
    "confidence",
    "detector",
    "detector_configuration",
    "annotation_campaign",
    "annotation_phase",
    "annotation_file_range",
    "annotation_task",
    "annotation",
    "annotation_validation",
    "acoustic_features",
    "session",
    "archive",
]
