# Generated by Django 3.2.25 on 2026-02-02 15:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [
        ("osmosewebsite", "0001_initial"),
        ("osmosewebsite", "0002_auto_20231124_1025"),
        ("osmosewebsite", "0003_auto_20231124_1037"),
        ("osmosewebsite", "0004_auto_20231124_1101"),
        ("osmosewebsite", "0005_auto_20231127_1508"),
        ("osmosewebsite", "0006_alter_teammember_options"),
        ("osmosewebsite", "0007_news"),
        ("osmosewebsite", "0008_auto_20231130_1754"),
        ("osmosewebsite", "0009_alter_news_osmose_member_authors"),
        ("osmosewebsite", "0010_collaborator_project"),
        ("osmosewebsite", "0011_rename_vignette_project_thumbnail"),
        ("osmosewebsite", "0012_project_collaborators"),
        ("osmosewebsite", "0013_collaborator_url"),
        ("osmosewebsite", "0007_auto_20231206_0954"),
        ("osmosewebsite", "0010_merge_20231206_1102"),
        ("osmosewebsite", "0011_rename_vignette_news_thumbnail"),
        ("osmosewebsite", "0014_merge_20231206_1444"),
        ("osmosewebsite", "0008_auto_20240103_1132"),
        ("osmosewebsite", "0012_merge_20240108_1138"),
        ("osmosewebsite", "0015_merge_20240108_1547"),
        ("osmosewebsite", "0016_alter_teammember_mail_address"),
        ("osmosewebsite", "0017_alter_teammember_biography"),
        ("osmosewebsite", "0018_alter_collaborator_options"),
        ("osmosewebsite", "0019_collaborator_show_on_aplose_home"),
        ("osmosewebsite", "0020_trap"),
        ("osmosewebsite", "0021_auto_20240909_0918"),
        ("osmosewebsite", "0022_project_metadatax_project"),
        ("osmosewebsite", "0023_project_contact"),
        ("osmosewebsite", "0024_scientifictalks_presenters"),
        ("osmosewebsite", "0025_alter_scientifictalk_intro"),
        ("osmosewebsite", "0026_add_scientist"),
        ("osmosewebsite", "0027_update_team_member"),
        ("osmosewebsite", "0028_add_bibliography"),
        ("osmosewebsite", "0029_add_bibliography_tag"),
        ("osmosewebsite", "0030_add_scientist_constraint"),
        ("osmosewebsite", "0031_alter_teammember_scientist"),
        ("osmosewebsite", "0032_update_bibliography_model"),
        ("osmosewebsite", "0033_alter_project_metadatax_project"),
        ("osmosewebsite", "0034_migrate_bibliography_to_metadatax"),
    ]

    initial = True

    dependencies = [
        ("common", "0006_clean"),
        ("acquisition", "0005_clean"),
    ]
    run_before = [
        ("common", "0008_refacto_common"),
        ("acquisition", "0006_refacto_common"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sorting level"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("thumbnail", models.URLField()),
                ("url", models.URLField(blank=True, null=True)),
                ("show_on_home_page", models.BooleanField(default=False)),
                ("show_on_aplose_home", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sorting level"
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                ("biography", models.TextField(blank=True, null=True)),
                ("picture", models.URLField()),
                (
                    "mail_address",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Mail address",
                    ),
                ),
                (
                    "research_gate_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Research Gate URL"
                    ),
                ),
                (
                    "personal_website_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Personal website URL"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="Github URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "is_former_member",
                    models.BooleanField(default=False, verbose_name="Is former member"),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="team_member",
                        to="common.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="ScientificTalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("thumbnail", models.URLField(default="")),
                (
                    "other_presenters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "osmose_member_presenters",
                    models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("body", tinymce.models.HTMLField()),
                ("thumbnail", models.URLField(default="")),
                (
                    "other_contacts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(blank=True, to="osmosewebsite.Collaborator"),
                ),
                (
                    "metadatax_project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_project",
                        to="acquisition.project",
                    ),
                ),
                (
                    "osmose_member_contacts",
                    models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
                ),
            ],
            options={
                "ordering": ["-end"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("body", tinymce.models.HTMLField()),
                ("date", models.DateField(blank=True, null=True)),
                ("thumbnail", models.URLField(default="")),
                (
                    "other_authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "osmose_member_authors",
                    models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
                ),
            ],
            options={
                "verbose_name_plural": "news",
                "ordering": ["-date"],
            },
        ),
    ]
