# Generated by Django 3.2.25 on 2026-01-28 16:54

import django.contrib.postgres.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("osmosewebsite", "0001_initial"),
        ("osmosewebsite", "0002_auto_20231124_1025"),
        ("osmosewebsite", "0003_auto_20231124_1037"),
        ("osmosewebsite", "0004_auto_20231124_1101"),
        ("osmosewebsite", "0005_auto_20231127_1508"),
        ("osmosewebsite", "0006_alter_teammember_options"),
        ("osmosewebsite", "0007_news"),
        ("osmosewebsite", "0008_auto_20231130_1754"),
        ("osmosewebsite", "0009_alter_news_osmose_member_authors"),
        ("osmosewebsite", "0010_collaborator_project"),
        ("osmosewebsite", "0011_rename_vignette_project_thumbnail"),
        ("osmosewebsite", "0012_project_collaborators"),
        ("osmosewebsite", "0013_collaborator_url"),
        ("osmosewebsite", "0007_auto_20231206_0954"),
        ("osmosewebsite", "0010_merge_20231206_1102"),
        ("osmosewebsite", "0011_rename_vignette_news_thumbnail"),
        ("osmosewebsite", "0014_merge_20231206_1444"),
        ("osmosewebsite", "0008_auto_20240103_1132"),
        ("osmosewebsite", "0012_merge_20240108_1138"),
        ("osmosewebsite", "0015_merge_20240108_1547"),
        ("osmosewebsite", "0016_alter_teammember_mail_address"),
        ("osmosewebsite", "0017_alter_teammember_biography"),
        ("osmosewebsite", "0018_alter_collaborator_options"),
        ("osmosewebsite", "0019_collaborator_show_on_aplose_home"),
        ("osmosewebsite", "0020_trap"),
        ("osmosewebsite", "0021_auto_20240909_0918"),
        ("osmosewebsite", "0022_project_metadatax_project"),
        ("osmosewebsite", "0023_project_contact"),
        ("osmosewebsite", "0024_scientifictalks_presenters"),
        ("osmosewebsite", "0025_alter_scientifictalk_intro"),
        ("osmosewebsite", "0026_add_scientist"),
        ("osmosewebsite", "0027_update_team_member"),
        ("osmosewebsite", "0028_add_bibliography"),
        ("osmosewebsite", "0029_add_bibliography_tag"),
        ("osmosewebsite", "0030_add_scientist_constraint"),
        ("osmosewebsite", "0031_alter_teammember_scientist"),
        ("osmosewebsite", "0032_update_bibliography_model"),
        ("osmosewebsite", "0033_alter_project_metadatax_project"),
        ("osmosewebsite", "0034_migrate_bibliography_to_metadatax"),
        ("osmosewebsite", "0035_rename_contact_teammember_person"),
    ]

    initial = True

    dependencies = [
        ("api", "0030_spectroconfig_name_dataset_unicity_constraint"),
        ("bibliography", "00002_make_information_nullable_by_default"),
        ("metadatax", "0022_auto_20240911_1902"),
        ("acquisition", "0003_auto_20250630_1401"),
        ("common", "0006_clean"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=255)),
                ("biography", models.TextField()),
                ("picture", models.URLField()),
                (
                    "mailAddress",
                    models.EmailField(max_length=254, verbose_name="Mail address"),
                ),
                (
                    "researchGateURL",
                    models.URLField(
                        blank=True, null=True, verbose_name="Research Gate URL"
                    ),
                ),
                (
                    "personalWebsiteURL",
                    models.URLField(
                        blank=True, null=True, verbose_name="Personal website URL"
                    ),
                ),
                (
                    "githubURL",
                    models.URLField(blank=True, null=True, verbose_name="Github URL"),
                ),
                (
                    "linkedinURL",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "isFormerMember",
                    models.BooleanField(default=False, verbose_name="Is former member"),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sorting level"
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("body", tinymce.models.HTMLField()),
                ("date", models.DateField(blank=True, null=True)),
                ("vignette", models.URLField(default="")),
            ],
            options={
                "verbose_name_plural": "news",
                "ordering": ["-date"],
            },
        ),
        migrations.RunSQL(
            sql="\n            INSERT INTO osmosewebsite_news (id, title, intro, body, date, vignette)\n            SELECT * FROM news\n        ",
        ),
        migrations.AddField(
            model_name="news",
            name="other_authors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="osmose_member_authors",
            field=models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
        ),
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sorting level"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("thumbnail", models.URLField()),
                ("show_on_home_page", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                ("show_on_aplose_home", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="githubURL",
            new_name="github_url",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="isFormerMember",
            new_name="is_former_member",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="linkedinURL",
            new_name="linkedin_url",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="mailAddress",
            new_name="mail_address",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="personalWebsiteURL",
            new_name="personal_website_url",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="researchGateURL",
            new_name="research_gate_url",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="vignette",
            new_name="thumbnail",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="name",
            new_name="firstname",
        ),
        migrations.AddField(
            model_name="teammember",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="mail_address",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Mail address"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("body", tinymce.models.HTMLField()),
                ("thumbnail", models.URLField(default="")),
                (
                    "osmose_member_contacts",
                    models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(blank=True, to="osmosewebsite.Collaborator"),
                ),
                (
                    "metadatax_project",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_project",
                        to="acquisition.project",
                    ),
                ),
                (
                    "other_contacts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "ordering": ["-end"],
            },
        ),
        migrations.CreateModel(
            name="ScientificTalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("intro", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("thumbnail", models.URLField(default="")),
                (
                    "osmose_member_presenters",
                    models.ManyToManyField(blank=True, to="osmosewebsite.TeamMember"),
                ),
                (
                    "other_presenters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Scientist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "institutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scientists",
                        to="osmosewebsite.Institution",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teammember",
            name="scientist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_members",
                to="osmosewebsite.scientist",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="firstname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="teammember",
            name="scientist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_members",
                to="osmosewebsite.scientist",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bibliography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("R", "In Review"),
                            ("P", "Published"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        help_text="Required for any published bibliography",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("S", "Software"),
                            ("A", "Article"),
                            ("C", "Conference"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True,
                        help_text="Required for an article",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("volumes", models.CharField(blank=True, max_length=255, null=True)),
                ("pages_from", models.PositiveIntegerField(blank=True, null=True)),
                ("pages_to", models.PositiveIntegerField(blank=True, null=True)),
                ("issue_nb", models.PositiveIntegerField(blank=True, null=True)),
                ("article_nb", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "publication_place",
                    models.CharField(
                        blank=True,
                        help_text="Required for a software",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("repository_url", models.URLField(blank=True, null=True)),
                (
                    "conference",
                    models.CharField(
                        blank=True,
                        help_text="Required for a conference",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "conference_location",
                    models.CharField(
                        blank=True,
                        help_text="Required for a conference (format: {City}, {Country})",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bibliography",
            },
        ),
        migrations.AddConstraint(
            model_name="bibliography",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("publication_date__isnull", False), ("publication_status", "P")
                    ),
                    models.Q(("publication_status", "P"), _negated=True),
                    _connector="OR",
                ),
                name="Published publication has a publication date",
            ),
        ),
        migrations.AddConstraint(
            model_name="bibliography",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", "A"), _negated=True),
                    models.Q(("journal__isnull", False), ("type", "A")),
                    _connector="OR",
                ),
                name="Article has required fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="bibliography",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", "S"), _negated=True),
                    models.Q(("publication_place__isnull", False), ("type", "S")),
                    _connector="OR",
                ),
                name="Software has required fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="bibliography",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", "C"), _negated=True),
                    models.Q(
                        ("conference__isnull", False),
                        ("conference_location__isnull", False),
                        ("type", "C"),
                    ),
                    _connector="OR",
                ),
                name="Conference has required fields",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="bibliography",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="osmosewebsite.bibliography",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="scientist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="osmosewebsite.scientist",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="institutions",
            field=models.ManyToManyField(
                blank=True,
                related_name="bibliography_authors",
                to="osmosewebsite.Institution",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("order", "bibliography")},
        ),
        migrations.CreateModel(
            name="BibliographyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="bibliography",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="osmosewebsite.BibliographyTag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scientist",
            unique_together={("first_name", "last_name")},
        ),
        migrations.AlterField(
            model_name="teammember",
            name="scientist",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_member",
                to="osmosewebsite.scientist",
            ),
        ),
        migrations.AddField(
            model_name="bibliography",
            name="conference_abstract_book_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bibliography",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("D", "Draft"),
                    ("R", "In Review"),
                    ("U", "Upcoming"),
                    ("P", "Published"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="publication_status",
            field=models.CharField(
                choices=[("U", "Upcoming"), ("P", "Published")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="type",
            field=models.CharField(
                choices=[
                    ("S", "Software"),
                    ("A", "Article"),
                    ("C", "Conference"),
                    ("P", "Poster"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadatax_project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="website_project",
                to="acquisition.project",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_member",
                to="common.person",
            ),
        ),
        migrations.AddField(
            model_name="scientist",
            name="metadatax_institutions",
            field=models.ManyToManyField(
                blank=True, related_name="scientists", to="common.Institution"
            ),
        ),
        migrations.RemoveField(
            model_name="scientist",
            name="institutions",
        ),
        migrations.RenameField(
            model_name="scientist",
            old_name="metadatax_institutions",
            new_name="institutions",
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="contact",
            new_name="person",
        ),
        migrations.AlterField(
            model_name="teammember",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_member",
                to="common.person",
            ),
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="scientist",
        ),
        migrations.RemoveField(
            model_name="bibliography",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Bibliography",
        ),
        migrations.DeleteModel(
            name="BibliographyTag",
        ),
        migrations.DeleteModel(
            name="Institution",
        ),
        migrations.DeleteModel(
            name="Scientist",
        ),
    ]
