# Generated by Django 3.2.25 on 2026-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0001_v3_0"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="contact",
            new_name="person",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="is_former_member",
        ),
        migrations.AddField(
            model_name="teammember",
            name="type",
            field=models.CharField(
                choices=[("A", "Active"), ("F", "Former"), ("C", "Collaborator")],
                default="A",
                max_length=1,
            ),
        ),
    ]
