# Generated by Django 3.2.25 on 2026-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0002_team_member_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="is_former_member",
        ),
    ]
