# Generated by Django 3.2.25 on 2026-01-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmosewebsite', '0034_migrate_bibliography_to_metadatax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='contact',
            new_name='person',
        ),
    ]
