# Generated by Django 3.2.25 on 2026-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osmosewebsite", "0035_rename_contact_teammember_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="type",
            field=models.CharField(
                choices=[("A", "Active"), ("F", "Former"), ("C", "Collaborator")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.RunSQL(
            sql="""
              UPDATE osmosewebsite_teammember m
              SET type='F'
              WHERE is_former_member;
          """,
            reverse_sql="""
                        UPDATE osmosewebsite_teammember m
                        SET is_former_member= true
                        WHERE type = 'F';
                        """,
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="is_former_member",
        ),
    ]
