query allCampaigns(
    $search: String
    $filter_isArchived: Boolean
    $filter_phase: AnnotationPhaseType
    $filter_ownerID: ID
    $filter_annotatorID: ID
    $filter_datasetID: ID
) {
    allAnnotationCampaigns(
        isArchived: $filter_isArchived
        phases_Phase: $filter_phase
        ownerId: $filter_ownerID
        phases_AnnotationFileRanges_AnnotatorId: $filter_annotatorID
        search: $search
        analysis_DatasetId: $filter_datasetID

        orderBy: "name"
    ) {
        results {
            id
            name
            deadline
            isArchived
            datasetName
            phases {
                results {
                    phase
                }
            }
            tasksCount
            completedTasksCount
            userTasksCount
            userCompletedTasksCount
        }
    }
}
