fragment Institution on InstitutionNode {
    __typename
    id
    name
}
fragment Team on TeamNode {
    __typename
    id
    name
    institution {
        name
    }
}
fragment Person on PersonNode {
    __typename
    id
    initialNames
    firstName
    lastName
}

query allInstitutions  { allInstitutions { results { ...Institution } } }
query allTeams($institutionId: ID)  { allTeams(institution: $institutionId) { results { ...Team } } }
query allPersons  { allPersons { results { ...Person } } }

mutation createContact($input: ContactMutationInput!) {
    contact(input: $input) {
        contact { id }
        errors {
            field
            messages
        }
    }
}

mutation createInstitution($input: InstitutionMutationInput!) {
    institution(input: $input) {
        institution { ... Institution }
        errors {
            field
            messages
        }
    }
}

mutation createTeam($input: TeamMutationInput!) {
    team(input: $input) {
        team { ...Team }
        errors {
            field
            messages
        }
    }
}

mutation createPerson($input: PersonInput!) {
    createPerson(input: $input) {
        person { ...Person }
        errors {
            field
            messages
        }
    }
}

fragment ContactType on ContentTypeNode {
    id
    model
}

query contactTypes {
    contentTypes(
        appLabel: "common"
        model_In: ["institution", "team", "person"]
    ) {
        results { ...ContactType }
    }
}