
mutation updateCampaignFeaturedLabels(
    $id: ID!
    $labelsWithAcousticFeatures: [ID]!
    $labelSetID: ID!
    $confidenceSetID: ID
    $allowPointAnnotation: Boolean!
) {
    updateAnnotationCampaign(input: {
        id: $id
        allowPointAnnotation: $allowPointAnnotation
        labelsWithAcousticFeatures: $labelsWithAcousticFeatures
        labelSet: $labelSetID
        confidenceSet: $confidenceSetID
    }) {
        errors {
            field
            messages
        }
    }
}
