fragment Dataset on DatasetNode {
    id
    name
    path
    description
    createdAt
    legacy
    analysisCount
    spectrogramCount
    start
    end
}

query allDatasets {
    allDatasets(orderBy: "-createdAt") {
        results {
            ...Dataset
            annotationCampaigns {
                edges {
                    node {
                        id
                        name
                        isArchived
                    }
                }
            }
        }
    }
}

query getDatasetByID($id: ID!) {
    datasetById(id: $id) {
        ...Dataset
        owner {
            displayName
        }
    }
}

query listDatasetsWithAnalysis {
    allDatasets(orderBy: "name") {
        results {
            id
            name
            spectrogramAnalysis(orderBy: "name") {
                results {
                    id
                    name
                    colormap {
                        name
                    }
                }
            }
        }
    }
}
