fragment FileRange on AnnotationFileRangeNode {
    id
    firstFileIndex
    lastFileIndex
    filesCount

    annotator {
        id
        displayName
    }

    completedAnnotationTasks: annotationTasks(status: Finished) {
        totalCount
    }
}


query listFileRanges($phaseID: ID) {
    allAnnotationFileRanges(annotationPhase: $phaseID) {
        results { ...FileRange }
    }
}

mutation createFileRange($input: AnnotationFileRangeCreateMutationInput!) {
    createFileRange(input: $input) {
        annotationFileRange { ...FileRange }
        errors {
            messages
            field
        }
    }
}

mutation updateFileRange($input: AnnotationFileRangeUpdateMutationInput!) {
    updateFileRange(input: $input) {
        annotationFileRange { ...FileRange }
        errors {
            field
            messages
        }
    }
}

mutation deleteFileRange($id: ID!) {
    deleteFileRange(id: $id) {
        error {
            field
            messages
        }
    }
}
